fail_fast: true
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: sveltekit-build
        name: sveltekit-build
        entry: npm run build
        language: system
        pass_filenames: false
